### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ghost** [MarshalX/SalienSnake#6]
INFO  [09:59:26] Account #0: Used the restoration of health!
Exception in thread Account #29:
Traceback (most recent call last):
  File "C:\Users\Takolp\AppData\Local\Programs\Python\Python36-32\lib\threading.py", line 916, in _bootstrap_i
nner
    self.run()
  File "SalienSnake.py", line 389, in run
    Game(self).play()
  File "SalienSnake.py", line 400, in play
    self.start_boss_game()
  File "SalienSnake.py", line 481, in start_boss_game
    response = self.player.report_boss_damage(damage_done, damage_taken, used_healing)['response']
TypeError: 'NoneType' object is not subscriptable

**Comment by MarshalX** [comment]
This was fixed 10 hours ago (https://github.com/MarshalX/SalienSnake/commit/e730ef1402ce5f03d9cdc9c33b73faade1aebfe4). Thank you!
